# Generated by Django 4.1.1 on 2022-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="batman.png", upload_to="profile_pics"),
        ),
    ]
